apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "5"
  creationTimestamp: "2024-09-26T22:53:38Z"
  generation: 5
  labels:
    app: bobvsworld
  name: bobvsworld
  namespace: bobvsworld
  resourceVersion: "107941538"
  uid: 795a783f-686d-43e4-94c5-37b539e4745f
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: bobvsworld
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: bobvsworld
    spec:
      containers:
      - image: docker.io/ivanlab/bobvsworld:latest
        imagePullPolicy: Always
        name: bobvsworld
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30